config/routes.rb
Snowbookssite::Application.routes.draw do

  root :to => 'webs#home'
  match '/weblog', to: 'webs#blog'
resources :webs do
  get 'author_show', :on => :member
  collection do
    get 'home'
    get 'about'
    get 'contact'
    get 'submissions'
    get 'rights'
    get 'catalogue'
    get 'blog'
    get 'author_index'
    get 'alphabetical'
    get 'single_cat'
  end
end
  resources :posts do
    resources :comments
  end

end

app/views/webs/_alphabetical_feature.html.haml
- summaries.sort_by{ |k, v| k["Title"] }.each do |feature|  
  %li.span2
    .thumbnail
      %a{ :href=> web_path(feature[:web]), :class => "no_hover_background"}
        = image_tag feature[:cover], :alt => feature[:book_number], :class => "product_image"
        %h5
          - feature.each do |heading,value|
            - next if heading.is_a? Symbol
            - next if heading == "Category"
            - next if heading == "Price"
            - next if heading == "Format"
            - next if heading == "Status"
            %br
            %span.summary_value
              = value
        %a{ :href => "#{amazon_url_helper(feature[:web].book, current_company() )}" } 
          = image_tag "#{static_root}/amazon_icon.png"
        = link_to image_tag("#{static_root}/add_to_shopping_cart.png"), web_path(feature[:web]) 
        %hr

app/views/webs/_contributor.html.haml
%h6
  About
  = sanitize contributor[:name]
%table
  %tr
    %p
      != strip_tags(contributor[:bio])

app/views/webs/_feature.html.haml
= will_paginate features, :renderer => BootstrapPagination::Rails   
#accordion2.accordion  
  - features.each_with_index do |(cat_name, array_of_books), i|  
    %h2
      %ul#myTab.nav.nav-tabs
        %li.active
          %a{"data-toggle" => "tab", :href => "#home"}= cat_name
      
      #myTabContent.tab-content
        #home.tab-pane.fade.in.active
          .row
            .category_section
            - array_of_books[0..5].each do |feature|
              = link_to image_tag(feature[:cover], :class => "product_image_tiny"), web_path(feature[:web])
            %section#category_fold  
              %details.animated
                %summary
                  Details 
                %p.gap
                  - array_of_books.sort_by{ |k, v| k["Author"] }.each do |feature|
                    %ul
                      %li.span3
                        .thumbnail
                          %a{ :href=> web_path(feature[:web]), :class => "no_hover_background"}
                            = image_tag feature[:cover], :alt => feature[:isbn_number], :class => "product_image"
                            %h5  
                              - feature.each do |heading,value|
                                - next if heading.is_a? Symbol
                                - next if heading == "Category"
                                - next if heading == "Price"
                                - next if heading == "Format"
                                - next if heading == "Status"
                                %br
                                %span.summary_value
                                  = value
                            %a{ :href => "#{amazon_url_helper(feature[:web].book, current_company() )}" } 
                              = image_tag "#{static_root}/amazon_icon.png"
                            = link_to image_tag("#{static_root}/add_to_shopping_cart.png"), web_path(feature[:web]) 
                            %hr

app/views/webs/_paypal.html.haml
%object
  %form{:target=> "paypal", :action=> "https://www.paypal.com/cgi-bin/webscr", :method=> "post" }
    %input{:type=> "image", :class=> "basket",
            :name => "submit", :alt => "Make payments with PayPal - it's fast, free and secure!",
            :src=> "#{(region == :uk) ? 'https://s3-eu-west-1.amazonaws.com/bibliocloudimages/static/ukbuy.jpg' : 'https://s3-eu-west-1.amazonaws.com/bibliocloudimages/static/overseasbuy.jpg'}" }
    %img{:alt=> " ", :src=> "https://www.paypal.com/en_GB/i/scr/pixel.gif", :width=> "1", :height=> "1" }
    %input{:type=> "hidden", :name=> "add", :value=> "1" }
    %input{:type=> "hidden", :name=> "cmd", :value=> "_cart" }
    %input{:type=> "hidden", :name=> "business", :value=> "#{company.email_address }" }
    %input{:type=> "hidden", :name=> "item_:name", :value=> "#{book.title}" }
    %input{:type=> "hidden", :name=> "item_number", :value=> "#{book.isbn}" }
    %input{:type=> "hidden", :name=> "amount", :value=> "#{price}" }
    %input{:type=> "hidden", :name=> "shipping", :value=> "0" }
    %input{:type=> "hidden", :name=> "no_shipping", :value=> "0" }
    %input{:type=> "hidden", :name=> "no_note", :value=> "1" }
    %input{:type=> "hidden", :name=> "currency_code", :value=> "GBP" }
    %input{:type=> "hidden", :name=> "lc", :value=> "GB" }
    %input{:type=> "hidden", :name=> "bn", :value=> "PP-ShopCartBF" }

app/views/webs/_rights_guide.html.haml
.row
  - collection.each do |work|
    .span9
      %h2
        = work.title
      %p
        %h5
          = "Rights territory:"
          - if work.contract
            = work.contract.territory 
            %p
              Rights controlled:
              - work.contract.righttypes.each do |righttype|
                = righttype.right_type
                |
      %p
        = "Rights sold:"
        - unless work.foreignrights.first
          All available
        - work.foreignrights.each do |right|
          - unless right.rightstype == "Translation" || right.rightstype.blank?
            = Righttype.type(right)
            = right.language 
            |
      - if work.books.first
        %p
          = Marketingtext.get_text(work.books.first, :blurb)
      %p
      - if work.books.first
        %h4 UK Editions: 
        -  work.books.each do |book|
          - present book do |book_presenter| #present method defined in application helper. 
            %p.med
              = book.isbn
              = book.translated_format
              = "#{book.default_contributor_first_name} #{book.default_contributor_last_name}"
              - if book.default_price_amount?
                = current_company_curr
                = book.default_price_amount
              = book_presenter.pretty_date(:pub_date)   
      %hr  
                        
    .span2
      - if work.books.first  
        - cover = work.books.first.supportingresources.last
        - if cover
          = image_tag cover.image.url(:thumb), {:class => 'product_image'}

app/views/webs/about.html.haml
.container
  .row
    %header.box_theme#page_title
      %h1 About us

  .row
    %aside.span4.box_theme#subtitle
      %h2
        About
        = "#{@company_name}" unless @company_name.nil?
      %p
        Read all about us.
    %section.span8
      .article.box_theme
        = raw Company.find(1).text( :about_us )

app/views/webs/alphabetical.html.haml
.container
  .row
    %header.box_theme#page_title
      %h1 Our books, A-Z
  .row
    %aside.span4.box_theme#subtitle
      %p 
        = "This page contains all of our books. They're arranged alphabetically. If you click on the cover, you'll see more information about that book. "
      %p
        = link_to "Browse by category instead.", webs_path 
      %p
        = link_to "Browse by author instead.", author_index_webs_path
      %p
        = link_to "Look at our official catalogue.", catalogue_webs_path
      = form_tag alphabetical_webs_path, method: :get do
        %p
          = text_field_tag :query, params[:query]
          = submit_tag "Search", name: nil, :class => 'btn-success-narrow'

    %section.span8    
      .article.box_theme
        = render :partial => "alphabetical_feature", :locals => { :summaries => @summaries }
        

app/views/webs/author_show.html.haml
.container

  .row
    %header.box_theme#page_title
      = "#{@contact.names_before_key} #{@contact.keynames}"
  .row
    %aside.span4.box_theme#subtitle
      %h2
        #{"About #{@contact.names_before_key} #{@contact.keynames} "}
      %p
        A few more details about #{"#{@contact.names_before_key}"}.

    %section.span8    
      .article.box_theme

        %p= @contact.biographical_note  
        - if @contact.biographical_note.blank? then
          - @features.each do |details|
            %p= details[:bio]
            - break unless details[:bio].blank?
        =render :partial => 'summary', :collection => @features

app/views/webs/blog.html.haml
.container
  .row
    %header.box_theme#page_title
      %h1 Our blog
  .row
    - if flash[:notice]
      .p.notice
        =flash[:notice]
  .row
    %aside.span4.box_theme#blog_links
      = form_tag posts_path, method: :get do
        %p
          = text_field_tag :query, params[:query]
          = submit_tag "Search", name: nil, :class => 'btn-success-narrow'
      %h2 Blog Archive
      - @post_months.each do |month, posts|
        %h4= month.strftime("%B %Y")
        %ul
          - posts.each do |post|
            %li.post_links
              = link_to post_path(post) do
                = raw sanitize strip_tags(post.title)
    %section.span8.blog_posts
      - @posts.limit(10).order('created_at DESC').each do |post|
        .article.box_theme
          %header
            %h2.blog_post_title
              = raw sanitize strip_tags(post.title)
          %p.posted_by
            = "posted on "
            %time{datetime: post.created_at.strftime('%FT$H:%M$z'), pubdate: ""}
              = post.created_at.strftime('%d %B %Y')
            - if post.user_id
              = "by #{post.user.first_name}"
          .blog_body
            = raw simple_format post.body
            %p
            - unless post.extended_body.blank?
              %details.animated
                %summary Read more...
                .blog_body
                  = raw simple_format post.extended_body
            %p
              = raw post.excerpt
            %hr
          %section#blog_comments
            = facebook_like_from_index(post)
            %p
              %details.animated
                %summary
                  = "#{pluralize(post.comments_count, 'comment')}"
                - unless post.comments_count==0
                  - post.comments.order('created_at asc').each do |comment|
                    %article#blog_comments
                      = raw sanitize simple_format comment.body
                      %footer.posted_by
                        = "by #{comment.author} on "
                        %time{datetime: post.created_at.strftime('%FT$H:%M$z'), pubdate: ""}
                          = comment.created_at.strftime('%d %B %Y')
                = semantic_form_for([post, post.comments.build]) do |f|
                  = f.input :body, :label => 'Add a comment'
                  = f.input :author, :label => 'Your name'
                  = f.input :email, :label => 'Your email (will not be published)'
                  = f.input :ip, :label => "To prove you are human, answer yes or no: was Jane Eyre an author?", :class => :narrow

                  = f.actions  do
                    = f.submit "Post comment", :class => 'save'
-if request.fullpath.match(/codicology/)
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "https://connect.facebook.net/en_US/all.js#xfbml=1&appId=239528472835438";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
  </script>
- elsif request.fullpath.match(/bibliocloud/)
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "https://connect.facebook.net/en_US/all.js#xfbml=1&appId=333040396780339";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

app/views/webs/catalogue.html.haml
.container
  .row
    %header.box_theme#page_title
      %h1 Catalogues
    %hr
  .row
    %aside.span4.box_theme#subtitle
      %h2
        Catalogues from
        = "#{@company_name}" unless @company_name.nil?
      %p
        Our catalogues. 

    %section.span8    
      .article.box_theme
        = raw Company.by_webname(request.subdomains.first).text( :catalogue )

app/views/webs/contact.html.haml
.container
  .row
    %header.box_theme#page_title
      %h1 Contact us
  .row
    %aside.span4.box_theme#subtitle
      %h2
        Contact Snowbooks

    %section.span8
      .article.box_theme
        = raw sanitize Company.find(1).text( :contact )

app/views/webs/index.html.haml
.container.books_index
  .row 
    %header.box_theme#page_title
      %h1 Our books
  .row 
    %aside.span4.box_theme#subtitle
      %p
        = link_to "Browse alphabetically instead.", alphabetical_webs_path
      %p
        = link_to "Browse by author instead.", author_index_webs_path
      %p
        = link_to "Look at our official catalogue.", catalogue_webs_path
      = form_tag webs_path, method: :get do
        %p
          = text_field_tag :query, params[:query]
          = submit_tag "Search", name: nil, :class => 'btn-success-narrow'  
      - @feature_root.each do |cat_name, array_of_books|  
        %p
          = link_to(cat_name  ,:controller=>"webs"  , :action=>:single_cat , :cat => cat_name )
          
    %section.span8    
      .article.box_theme
        = render :partial => "feature", :locals => { :features => @features }
      

app/views/webs/rights.html.haml
.container
  .row
    %header.box_theme#page_title
      %h1 Rights
  .row
    %aside.span4.box_theme#subtitle
      %h2 
        Licensing rights from
        = "#{@company_name}" unless @company_name.nil?
      %p
        Information about the rights we hold in our titles, and how to sub-license from us. 
      = raw Company.by_webname(request.subdomains.first).text( :contact )

    %section.span8    
      .article.box_theme
        = render :partial => 'rights_guide', :locals => { :collection => Work.where("client_id = ? and status = ?", Client.find_by_webname(request.subdomains.first).id, "Live"), :user_company => @company_name}

app/views/webs/single_cat.html.haml
.container
  .row
    %header.box_theme#page_title
      %h1 Our books
  .row
    %aside.span4.box_theme#subtitle
      %p
        = link_to "Browse alphabetically instead.", alphabetical_webs_path
      %p
        = link_to "Browse by author instead.", author_index_webs_path
      %p
        = link_to "Look at our official catalogue.", catalogue_webs_path
      = form_tag webs_path, method: :get do
        %p
          = text_field_tag :query, params[:query]
          = submit_tag "Search", name: nil, :class => 'btn-success-narrow'  
      - @feature_root.each do |cat_name, array_of_books|  
        %p
          = link_to(cat_name  , :controller=>"webs"  , :action=>:single_cat       , :cat => cat_name)
    %section.span8    
      .article.box_theme
        %h2
          = @cat_name
        %hr
        - @single_cat.sort_by{ |k, v| k["Author"] }.each do |feature|
          %li.span2
            .thumbnail
              %a{ :href=> web_path(feature[:web]), :class => "no_hover_background"}
                = image_tag feature[:cover], :alt => feature[:book_number], :class => "product_image"
                %h5  
                  - feature.each do |heading,value|
                    - next if heading.is_a? Symbol
                    - next if heading == "Category"
                    - next if heading == "Price"
                    - next if heading == "Format"
                    - next if heading == "Status"
                    %br
                    %span.summary_title
                      = heading + ':'
                    %span.summary_value
                      = value
                %a{ :href => "#{amazon_url_helper(feature[:web].book, current_company() )}" } 
                  = image_tag "#{static_root}/amazon_icon.png"
                = link_to image_tag("#{static_root}/add_to_shopping_cart.png"), web_path(feature[:web]) 
                %hr