config/routes.rb
Snowbookssite::Application.routes.draw do

  root :to => 'webs#home'
  match '/weblog', to: 'webs#blog'
resources :webs do
  get 'author_show', :on => :member
  collection do
    get 'home'
    get 'about'
    get 'contact'
    get 'submissions'
    get 'rights'
    get 'catalogue'
    get 'blog'
    get 'author_index'
    get 'alphabetical'
    get 'single_cat'
  end
end
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  client_id   :integer
#  contact_id  :integer
#  author      :string(255)
#  email       :string(255)
#  ip          :string(255)
#  url         :string(255)
#  body        :text
#  published   :boolean
#  post_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  original_id :integer
#

class Comment < ActiveRecord::Base
  attr_accessible :author, :body, :client_id, :contact_id, :email, :ip, :post_id, :published, :url, :user_id, :created_at, :updated_at
  belongs_to :post, counter_cache: true
  has_paper_trail

  validates_presence_of :email
  validates_presence_of :body
  validates_presence_of :author
  validates_presence_of :ip

  validate :captcha_must_be_correct

  def captcha_must_be_correct
    errors.add(:ip, "Try again") unless
     ip.match(/no.?/i)

  end
end

app/controllers/comments_controller.rb
# -*- encoding : utf-8 -*-
class CommentsController < ClienttemplatesController

  skip_before_filter :set_ariane_home
  skip_before_filter :set_ariane
  skip_authorization_check :only => [:show, :new, :update, :create, :index]
  skip_before_filter :authenticate_user!, :only => [:show, :new, :update, :create, :index]
  skip_before_filter :current_user_variables, :only => [:show, :new, :update, :create, :index]

  layout 'web', :only => [:show, :new, :update, :create, :index]

  respond_to :html, :csv, :xml

  def index
    @post = Post.find(params[:post_id])

    @comments = @post.comments
  end

  def edit
    singular_action(__method__)
  end

  def new
    new_action(__method__)
  end

  def create
     @post = Post.find(params[:post_id])
     @comment = @post.comments.create(params[:comment])
     if @comment.save
       redirect_to(:back, :notice => "Comment saved.")
     else
       redirect_to(:back, :notice => "Comment not saved: please try again.")
     end
   end

     def update
    @comment           = Comment.new(params[:comment])

  end

  def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy

      respond_to do |format|
        format.html { redirect_to :back }
        format.xml { head :ok }
      end

  end

end

app/views/comments/_form.html.haml
= semantic_form_for(@comment) do |f| 
  = f.input :body


  = f.actions  do
    = f.submit "#{t('save')}", :class => 'save'

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>User</th>
    <th>Client</th>
    <th>Contact</th>
    <th>Author</th>
    <th>Email</th>
    <th>Ip</th>
    <th>Url</th>
    <th>Body</th>
    <th>Published</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user_id %></td>
    <td><%= comment.client_id %></td>
    <td><%= comment.contact_id %></td>
    <td><%= comment.author %></td>
    <td><%= comment.email %></td>
    <td><%= comment.ip %></td>
    <td><%= comment.url %></td>
    <td><%= comment.body %></td>
    <td><%= comment.published %></td>
    <td><%= comment.post_id %></td>
    <td><%= link_to 'Destroy', [@post, comment], confirm: 'Are you sure?', method: :delete %></td>
    

    
    
    
  </tr>
<% end %>
</table>

<br />

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Client:</b>
  <%= @comment.client_id %>
</p>

<p>
  <b>Contact:</b>
  <%= @comment.contact_id %>
</p>

<p>
  <b>Author:</b>
  <%= @comment.author %>
</p>

<p>
  <b>Email:</b>
  <%= @comment.email %>
</p>

<p>
  <b>Ip:</b>
  <%= @comment.ip %>
</p>

<p>
  <b>Url:</b>
  <%= @comment.url %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Published:</b>
  <%= @comment.published %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/update.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>