config/routes.rb
Snowbookssite::Application.routes.draw do

  root :to => 'webs#home'
  match '/weblog', to: 'webs#blog'
resources :webs do
  get 'author_show', :on => :member
  collection do
    get 'home'
    get 'about'
    get 'contact'
    get 'submissions'
    get 'rights'
    get 'catalogue'
    get 'blog'
    get 'author_index'
    get 'alphabetical'
    get 'single_cat'
  end
end
  resources :posts do
    resources :comments
  end

end

app/views/layouts/_webheader.html.haml
- if request.subdomains.first == "bibliocloud"
  = render "layouts/helpheader"
- else
  .navbar.navbar-fixed-top.box_theme
    .navbar-inner
      .nav-container
        %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => "/webs/home"}
          Snowbooks
        .nav-collapse
          %ul.nav
            %li.active
              =link_to "Home", home_webs_path
            %li
              =link_to "About", about_webs_path
            %li
              =link_to "Contact", contact_webs_path
            %li
              =link_to "Submissions", submissions_webs_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Books
                %b.caret
              %ul.dropdown-menu
                %li
                  =link_to "By category", webs_path
                %li
                  =link_to "By author", author_index_webs_path
                %li
                  =link_to "Alphabetical listing", alphabetical_webs_path

              %li
                =link_to "Blog", blog_webs_path

app/views/layouts/_webstylesheets.html.erb
<!--[if lt IE 9]>
<script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--[if lt IE 7]>
<script type="text/javascript" src="js/jquery/jquery.js"></script>
<script type="text/javascript" src="js/jquery/jquery.dropdown.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html.no-js
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    <meta name="google-site-verification" content="eVrRPajQ7fN0DL2hgfzCIM5JNKCTa9ZkiXwYj6OY6vk" />
    <!--[if lt IE 9]>
    <script src="https://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <script>
    var e = ("abbr,article,aside,audio,canvas,datalist,details," +
    "figure,footer,header,hgroup,mark,menu,meter,nav,output," +
    "progress,section,time,video").split(',');
    for (var i = 0; i < e.length; i++) {
    document.createElement(e[i]);
    }
    </script>
    <![endif]-->

    %title= Client.find(1).webname.capitalize
    = stylesheet_link_tag    "application-snowbooks", :media => "all"
    %body
      = render 'layouts/webheader'
      = yield
    = render 'layouts/webfooter'

    = javascript_include_tag "application"
    = csrf_meta_tags

app/views/layouts/web.html.haml
!!!
%html.no-js
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    <meta name="google-site-verification" content="eVrRPajQ7fN0DL2hgfzCIM5JNKCTa9ZkiXwYj6OY6vk" />
    <!--[if lt IE 9]>
    <script src="https://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <script>
    var e = ("abbr,article,aside,audio,canvas,datalist,details," +
    "figure,footer,header,hgroup,mark,menu,meter,nav,output," +
    "progress,section,time,video").split(',');
    for (var i = 0; i < e.length; i++) {
    document.createElement(e[i]);
    }
    </script>
    <![endif]-->

    %title= Client.find_by_webname(request.subdomains.first).webname.capitalize if request.subdomains.first
    = stylesheet_link_tag    "application-snowbooks", :media => "all"
    %body
      = render 'layouts/webheader'
      = yield
    = render 'layouts/webfooter'

    = javascript_include_tag "application"
    = csrf_meta_tags